apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot-pong-ingress
  labels:
    app: iot-pong
  annotations:
    traefik.ingress.kubernetes.io/rewrite-target: /
    traefik.ingress.kubernetes.io/router.middlewares: mw-iot-pong@dev
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /app
        pathType: Prefix
        backend:
          service:
            name: iot-pong-svc
            port:
              number: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: mw-iot-pong
  namespace: dev
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /app